### ISSUE TITLE
Baikal + PHP7.0 + NGinX = ServerException Error 500

### ISSUE THREAD

**Issue by mr-bigbang** [andig/carddav2fb#60] opened 2018-09-29 20:31 UTC
I'm running Baikal 0.4.6 with php7.0-fpm (Version PHP 7.0.30-0+deb9u1 on Debian/Raspbian Strech 9.4) and NGinX 1.10.3
Syncing contacts via CardDAV-Sync (on Android) works perfectly fine. When trying to run the script ```$ php carddav2fb.php download``` I get a ServerException
```
root@<server>:/srv/carddav2fb# php carddav2fb.php download -vvv
Downloading vCard(s) from account <user>
    0 [>---------------------------] < 1 sec 2.0 MiB
In RequestException.php line 113:

  [GuzzleHttp\Exception\ServerException (500)]
  Server error: `PROPFIND https://<server>/card.php/addressbooks/<user>/<addressbook>/` resulted in a `500 Internal Ser
  ver Error` response:
  <?xml version="1.0" encoding="utf-8"?>
  <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
    <s:sabredav-version>3 (truncated...)


Exception trace:
 GuzzleHttp\Exception\RequestException::create() at /srv/carddav2fb/vendor/guzzlehttp/guzzle/src/Middleware.php:66
 GuzzleHttp\Middleware::GuzzleHttp\{closure}() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:203
 GuzzleHttp\Promise\Promise::callHandler() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:156
 GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/TaskQueue.php:47
 GuzzleHttp\Promise\TaskQueue->run() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:246
 GuzzleHttp\Promise\Promise->invokeWaitFn() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:223
 GuzzleHttp\Promise\Promise->waitIfPending() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:267
 GuzzleHttp\Promise\Promise->invokeWaitList() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:225
 GuzzleHttp\Promise\Promise->waitIfPending() at /srv/carddav2fb/vendor/guzzlehttp/promises/src/Promise.php:62
 GuzzleHttp\Promise\Promise->wait() at /srv/carddav2fb/vendor/guzzlehttp/guzzle/src/Client.php:106
 GuzzleHttp\Client->send() at /srv/carddav2fb/src/CardDav/Backend.php:251
 Andig\CardDav\Backend->query() at /srv/carddav2fb/src/CardDav/Backend.php:120
 Andig\CardDav\Backend->getVcards() at /srv/carddav2fb/src/functions.php:39
 Andig\download() at /srv/carddav2fb/src/DownloadCommand.php:55
 Andig\DownloadCommand->execute() at /srv/carddav2fb/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /srv/carddav2fb/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /srv/carddav2fb/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /srv/carddav2fb/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /srv/carddav2fb/carddav2fb.php:19

download [-i|--image] [-r|--raw RAW] [-c|--config CONFIG] [--] [<filename>]
```

The exact error message (according to Wireshark) is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>3.1.3</s:sabredav-version>
  <s:exception>ErrorException</s:exception>
  <s:message>stream_get_contents() expects parameter 2 to be integer, string given</s:message>
</d:error>
```

I narrowed the problem down to an invalid Content-Length HTTP-Header being passed to PHP7.0-FPM. When adding the following code in **src/CardDav/Backend.php** line **242** (after the initialization of $request in the method query()), the problem no longer occurs:
```php
$request = $request->withHeader('Content-Length', 0);
```
As far as I can tell, the actual length of the content is irrelevant.

Can someone verify the problem?

PS: Is it possible to expand the actual error message and not have it truncated in the -vvv output? Getting the error message out of Wireshark was a huge pain...

**Comment by ger82** [comment] 2018-12-14 11:21
Die aktuelle Baikal Version ist 0.50. 
Aber Baikal wird nicht leider mehr gepflegt, somit bin ich selbst auf owncloud umgestiegen.

**Comment by derwok** [comment] 2019-01-04 18:02
Hi,
I had the same issue with Baikal - but I could solve it. 
Good news: solution below.

## Root cause:
* Newest version of Baikal is 0.4.6 - see here: https://github.com/sabre-io/Baikal/releases
* Baikal 0.4.6 includes the sub module sabre-io/http version 4.2.1
* The http sub module in version 4.2.1 was causing the issue described above. See issue 72 in their repo: https://github.com/sabre-io/http/issues/72
* The issue 72 was fixed in version 4.2.2 of the http sub module - which UNFORTUNATELY never made it into a new Baikal release. Because there was no release after 0.4.6

## My solution:
As I did not know how to update the sabre-io `http module` inside my running Baikal instance I simply decided I do a local patch - because the impact of the patch seemed low.

So, I looked at what they changed to fix the issue - it was only a three lines in `lib/Message.php`:
https://github.com/sabre-io/http/commit/9cf0c48264176b34da485833ec9e4aca36d49d54
In my installation this file was stored here: 
`baikalroot/vendor/sabre/http/lib/Message.php`

## One more hint: 
Additionally I had to tell carddav2fb in config.php to use "digest" mode with the Baikal server, as this seems the default for Baikal.

As the above issue is fixed in Baikal/Sabre (but unfortunately not put in a release, yet) I would suggest to CLOSE THIS ISSUE here.

**Comment by derwok** [comment] 2019-01-06 10:48
## Alternative approach to update sabre/http from 4.2.1 to 4.2.2
If you don't like direkt hacking of PHP files as described in the "My solution" above...
I just discovered this post here: 
http://sabre.io/blog/2016/sabre-http-4.2.2-release/

So, in theory (not tested!), you might install a normal Baikal 0.4.6.
**First backup your baikal-root (with the Specifc sub directory in it)!!**

Then edit `baikalroot/vendor/sabre/dav/composer.json`

from:
```
    "require": {
        [...]
         "sabre/http" : "^4.2.1",
```
to:
```
    "require": {
        [...]
         "sabre/http" : "^4.2",
```

Then perform in `baikalroot` directory
* Download/installation of `composer.phar` https://getcomposer.org/download/ 
* Then run `php composer.phar update`
* Check `baikalroot/vendor/sabre/http/CHANGELOG.md` if you are now on sabre/http 4.2.2

Still I think, we can close this carddav2fb issue here, as this is problem is fixed in Baikal & sabre/dav

## One last thing
Baikal & sabre/dav development is on hold, as described in this blog post:
https://evertpot.com/sabredav-eol/
So, maybe it's time to head over to NextCloud or OwnCloud some day?

**Comment by andig** [comment] 2019-01-06 12:02
> I narrowed the problem down to an invalid Content-Length HTTP-Header being passed to PHP7.0-FPM. When adding the following code in src/CardDav/Backend.php line 242 (after the initialization of $request in the method query()), the problem no longer occurs:

@mr-bigbang I don't like forcing a wrong 0 content-length. Could you clarify in how far the content length is currently invalid?

**Comment by andig** [comment] 2019-01-26 09:50
Closed due to inactivity.

**Closed by andig** 2019-01-26 09:50 UTC
