### ISSUE TITLE
Unexpected behaviour when using "run" and when using "-i" flag

### ISSUE THREAD

**Issue by pucicu** [andig/carddav2fb#237] opened 2021-12-13 22:43 UTC
I would like to use the tool for sync the Baikal-based addressbook at a NAS to a FritzBox. Because of the upgrade to DSM 7, the old version of carddav2fb (from jens-maus) does not run anymore.

The workflow now runs smoothly when I use first`carddav2fb download test`, then convert `carddav2fb convert test test.xml`and then upload `carddav2fb upload test.xml`. As far as I understand, the `run` command would do these three steps together. But when I use `carddav2fb run` the tool tries to download the addressbooks from the FritzBox instead from the NAS and stops with an error 
```
Downloading recent FRITZ!Box phonebook
Save internal data from recent FRITZ!Box phonebook!

In functions.php line 74:
Could not connect to ftp server fritz.box for upload
```
This behaviour is not what I would expect.

The same (or similar) happens when I use the `-i`flag for the command `convert`.

**Comment by andig** [comment] 2021-12-14 06:31
So you‘re basically saying that you can specify your own server using `download` but not using `run`?

**Comment by pucicu** [comment] 2021-12-14 06:33
exactly. the same behaviour on two different machines (directly calling the tool from the NAS and from a macOS).

**Comment by blacksenator** [comment] 2021-12-14 06:57
This not a bug - it´s a feature! carddav2fb downloads FRITZ!Box telephone book in the first step to save FRITZ!Box-specific data: internal numbers, quickdial or vanity information. This information are saved in the internal FRITZ!Box memory using ftp.

**Comment by pucicu** [comment] 2021-12-14 07:13
ah, ok, I see. There was no information about this feature. Now it works.﻿

**Comment by blacksenator** [comment] 2021-12-14 07:19
@pucicu: I recommend to have a look into my forks [wiki](https://github.com/blacksenator/carddav2fb/wiki)

**Comment by pucicu** [comment] 2021-12-14 07:20
perhaps the error message is then misleading ("Could not connect to ftp server fritz.box for upload"). I guess, it should refer to download?

Do you have a guide for setting the FritzBox to allow the download via FTP? The download from the FritzBox does not work when using option `-i` (although the upload works well).

**Comment by pucicu** [comment] 2021-12-14 07:23
> @pucicu: I recommend to have a look into my forks [wiki](https://github.com/blacksenator/carddav2fb/wiki)

Oh, wow. I have to look at your fork. Thanks for this hint!

**Comment by blacksenator** [comment] 2021-12-14 07:24
Please close this issue and let´s discuss further [here](https://www.ip-phone-forum.de/threads/carddav-to-fritzbox-2-0-aka-carddav2fb.298117/)

**Closed** 2021-12-14 07:26 UTC
